services:
  - type: web
    name: appointmentapp
    plan: free
    env: docker
    repo: https://github.com/SMG7780noob/appointment_site_mongo
    region: singapore
    buildCommand: ""
    startCommand: ""
    autoDeploy: true
