services:
  - type: web
    name: appointmentapp
    env: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MongoSettings__ConnectionString
        sync: false
      - key: MongoSettings__DatabaseName
        value: appointmentdb
      - key: MongoSettings__CollectionName
        value: appointments
